---
- hosts: localhost
  connection: local
  tasks:
    - name: create bin directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.local/bin"
    - name: checkout tpm
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
        update: yes
        version: master
    - name: link tmux.conf
      file:
        state: link
        src: "{{ playbook_dir }}/.tmux.conf"
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
    - name: install tpm plugins
      shell:
        cmd: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins"
        creates: "{{ ansible_env.HOME }}/.tmux/plugins/tmux-sensible/sensible.tmux"
      environment:
        TMUX_PLUGIN_MANAGER_PATH: "{{ ansible_env.HOME }}/.tmux/plugins"
    - name: create neovim configuration directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.config/nvim"
    - name: link init.vim
      file:
        state: link
        src: "{{ playbook_dir }}/config/nvim/init.vim"
        dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    - name: create vim-plug directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    - name: download vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
    - name: install neovim plugins via vim-plug
      shell:
        cmd: nvim --headless +PlugInstall +UpdateRemotePlugins +qall
        creates: "{{ ansible_env.HOME }}/.config/nvim/plugged/vim-sensible/README.markdown"
    - name: link npmrc
      file:
        state: link
        src: "{{ playbook_dir }}/.npmrc"
        dest: "{{ ansible_env.HOME }}/.npmrc"
    - name: create starship directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.config/starship"
    - name: link starship.conf
      file:
        state: link
        src: "{{ playbook_dir }}/config/starship.toml"
        dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    - name: link starship tmux.conf
      file:
        state: link
        src: "{{ playbook_dir }}/config/starship/tmux.toml"
        dest: "{{ ansible_env.HOME }}/.config/starship/tmux.toml"
    - name: create lxterminal directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.config/lxterminal"
    - name: link lxterminal configuration
      file:
        state: link
        src: "{{ playbook_dir }}/config/lxterminal/lxterminal.conf"
        dest: "{{ ansible_env.HOME }}/.config/lxterminal/lxterminal.conf"
    - name: create alacritty directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.config/alacritty"
    - name: link alacritty configuration
      file:
        state: link
        src: "{{ playbook_dir }}/config/alacritty/alacritty.yml"
        dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
    - name: link scripts
      file:
        state: link
        src: "{{ playbook_dir }}/local/bin/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/{{ item }}"
      loop:
        - chromium
        - com.slack.Slack
        - starship-tmux
        - ttyd-webgl-solarized-dark
    - name: create applications directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.local/share/applications"
    - name: link desktop files
      file:
        state: link
        src: "{{ playbook_dir }}/local/share/applications/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.local/share/applications/{{ item }}"
      loop:
        - chromium.desktop
        - com.slack.Slack.desktop
    - name: create fonts directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.local/share/fonts"
    - name: download font Sauce Code Pro Nerd Font Complete Mono
      get_url:
        url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/SourceCodePro/Regular/complete/Sauce%20Code%20Pro%20Nerd%20Font%20Complete%20Mono.ttf
        dest: "{{ ansible_env.HOME }}/.local/share/fonts/Sauce Code Pro Nerd Font Complete Mono.ttf"
